// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asoguzidnslzqpcgrisz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzb2d1emlkbnNsenFwY2dyaXN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MTMyOTIsImV4cCI6MjA1NjA4OTI5Mn0.eSwXvR6XWkwZ3JUOEqY-4wegOmWWVc1KCK1EmbKYhEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);